apps/friend/urls.py
from django.conf.urls import url
from . import views
# from django.contrib import admin
app_name = 'friend'
urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^add$', views.add, name = 'add'),
    url(r'^block$', views.block, name = 'block'),
    url(r'^list$', views.list, name = 'list'),
    url(r'^make_friend/(?P<id>\d+)$', views.make_friend, name = 'make_friend'),
    url(r'^remove/(?P<id>\d+)$', views.remove, name = 'remove'),
    url(r'^remove_block/(?P<id>\d+)$', views.remove_block, name = 'remove_block'),
    url(r'^make_block/(?P<id>\d+)$', views.make_block, name = 'make_block'),
    url(r'^profile/(?P<id>\d+)$', views.profile, name = 'profile'),
    # url(r'^info/(?P<id>\d+)$', views.info, name = 'info'),
    # url(r'^edit/(?P<id>\d+)$', views.edit, name = 'edit'),
    # url(r'^change/$', views.change, name = 'change'),

]

apps/login/urls.py
from django.conf.urls import url
from . import views
# from django.contrib import admin
app_name = 'login'
urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^register$', views.register, name = 'reg'),
    url(r'^login$', views.login, name = 'login'),
    url(r'^logout$', views.logout, name = 'logout'),

]

main/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.login.urls', namespace = 'login')),
    url(r'^friend/', include('apps.friend.urls', namespace='friend')),
]

apps/friend/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from ..login.models import User

# Create your models here.


class FriendManager(models.Manager):
    def make_friend(self, user, friend):
        if len(Friend.objects.filter(userr_id=user).filter(usera_id=friend))>0:
            print 'no'
            return None
        else:
            friend = Friend.objects.create(userr_id=user, usera_id=friend)
            other = Friend.objects.create(userr_id=friend.id, usera_id=user)
            print 'yes'
            friend.save()
            other.save()
            return friend

    def remove_friend(self, user, friend):
        Friend.objects.filter(userr_id=user).filter(usera_id=friend).delete()

        return

    def grab_friend(self, user):
        results = {'users':None, 'friends':None}
        user = User.objects.get(id=user)
        try:
            users = User.objects.all()
            potentials = []
            for potential in users:
                if (potential.id != user.id):
                    potentials.append(potential)
        except:
            users = None

        try:
            friends = Friend.objects.filter(userr=user)
            made_friends = []
            for friend in friends:
                made_friends.append(friend.usera)
            others = []
            for potential in potentials:
                if (potential not in made_friends):
                    others.append(potential)
        except:
            friends = None

        results['users'] = others
        results['friends'] = made_friends
        return results

class BlockManager(models.Manager):
    def make_block(self, user, friend):
        if len(Block.objects.filter(blokr_id=user).filter(bloka_id=friend))>0:
            return None
        else:
            friend = Block.objects.create(blokr_id=user, bloka_id=friend)
            other = Block.objects.create(blokr_id=friend.id, bloka_id=user)
            friend.save()
            other.save()
            return friend

    def remove_block(self, user, friend):
        Block.objects.filter(blokr_id=user).filter(bloka_id=friend).delete()

        return

    def grab_block(self, user):
        results = {'blockers':None, 'block':None}
        user = User.objects.get(id=user)
        try:
            users = User.objects.all()
            potentials = []
            for potential in users:
                if (potential.id != user.id):
                    potentials.append(potential)
        except:
            users = None

        try:
            blocks = Block.objects.filter(blokr=user)
            made_blocks = []
            for block in blocks:
                made_blocks.append(block.bloka)
            others = []
            for potential in potentials:
                if (potential not in made_blocks):
                    others.append(potential)
        except:
            blocks = None

        results['blockers'] = others
        results['block'] = made_blocks
        return results


class Friend(models.Model):
    userr = models.ForeignKey(User, related_name='userf_request')
    usera = models.ForeignKey(User, related_name='userf_acceptor')
    objects = FriendManager()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Block(models.Model):
    blokr = models.ForeignKey(User, related_name='userb_request')
    bloka = models.ForeignKey(User, related_name='userb_acceptor')
    objects = BlockManager()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/friend/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from ..login.models import User
from django.contrib import messages
from .models import Friend, Block


# Create your views here.
def index(request):
    if 'logged' not in request.session:
        return redirect('login:index')
    else:
        try:
            context = {
                    'user': User.objects.get(id=int(request.session['logged'])),
                    'recents': User.objects.order_by('-pk')[2],
                    'more' : User.objects.order_by('-pk')[1],
                    'most' :User.objects.order_by('-pk')[0],
                }
            return render(request, 'friend/index.html', context)
        except:
            return redirect('login:index')


def list(request):
    if 'logged' not in request.session:
        return redirect('login:index')
    else:
        user = int(request.session['logged'])
        grab = Friend.objects.grab_friend(user)
        grab_blocks = Block.objects.grab_block(user)
        others = grab['users']
        block = grab_blocks['block']
        friends = grab['friends']
        context = {
            'logged': User.objects.get(id=int(request.session['logged'])),
            'users' : others,
            'friends': friends,
            'blocks':block,
        }
        return render(request, 'friend/list.html',context)

def add(request):
    if 'logged' not in request.session:
        return redirect('login:index')
    else:
        user = int(request.session['logged'])
        grab = Friend.objects.grab_friend(user)
        others = grab['users']
        friends = grab['friends']
        context = {
            'logged': User.objects.get(id=int(request.session['logged'])),
            'users' : others,
            'friends': friends,
        }
        return render(request, 'friend/add.html', context)

def block(request):
    if 'logged' not in request.session:
        return redirect('login:index')
    else:
        user = int(request.session['logged'])
        grab = Block.objects.grab_block(user)
        others = grab['blockers']
        block = grab['block']
        context = {
            'logged': User.objects.get(id=int(request.session['logged'])),
            'users' : others,
            'block': block,
        }
    return render(request, 'friend/block.html', context)

def make_friend(request, id):
    if 'logged' not in request.session:
        return redirect('login:index')
    user = int(request.session['logged'])
    friend = int(id)
    friend_make = Friend.objects.make_friend(user, friend)
    return redirect('friend:add')

def remove(request, id):
    if 'logged' not in request.session:
        return redirect('login:index')
    user = int(request.session['logged'])
    friend = int(id)
    remove_friend = Friend.objects.remove_friend(user, friend)
    return redirect('friend:list')

def make_block(request, id):
    if 'logged' not in request.session:
        return redirect('login:index')
    user = int(request.session['logged'])
    friend = int(id)
    block_make = Block.objects.make_block(user, friend)
    return redirect('friend:block')

def remove_block(request, id):
    if 'logged' not in request.session:
        return redirect('login:index')
    user = int(request.session['logged'])
    friend = int(id)
    remove_block = Block.objects.remove_block(user, friend)
    return redirect('friend:list')

def profile(request, id):
    if 'logged' not in request.session:
        return redirect('login:index')
    friend = User.objects.get(id=id)
    context = {
        'friend':friend
    }
    return render(request, 'friend/profile.html', context)

apps/friend/templates/friend/add.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>People you think you want to be friends with</h1>
    <a href="{% url 'friend:index' %}">Home</a>

    <br> <br>
    {{logged.name}}
    {% for user in users%}
    <table>
        <tr>
          <td></td>
        </tr>
      <tr>
        <td><a href="{% url 'friend:profile' id=user.id %}">{{user.first_name}}</a></td>
        <td>{{user.last_name}}</td>
        <td><a href="{% url 'friend:make_friend' id=user.id %}">Add Friend</a></td>
      </tr>
    </table>
    {% endfor %}


  </body>
</html>

apps/friend/templates/friend/block.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>People that you want nothing to do with</h1>
    <a href="{% url 'friend:index' %}">Home</a>


    <br> <br>

    {% for user in users%}

    <table>
      <tr>
        <td><a href="{% url 'friend:profile' id=user.id %}">{{user.first_name}}</a></td>
        <td>{{user.last_name}}</td>
        <td><a href="{% url 'friend:make_block' id=user.id %}">Block Bish</a></td>
      </tr>
    </table>


    {% endfor %}
  </body>
</html>

apps/friend/templates/friend/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome, {{user.first_name}}</h1>
    <h2>Welcome to friend book where what we do is just add friends</h2>
    <a href="{% url 'friend:list' %}">View your current friends list</a>
    <p style="display: inline-block">|</p>
    <a href="{% url 'friend:add' %}">Add A Friend</a>
    <p style="display: inline-block">|</p>
    <a href="{% url 'friend:block' %}">Block a User cause they suck</a>
    <p style="display: inline-block">|</p>
    <a href="{% url 'login:logout' %}">Logout</a>


    <h2>Most of our recent additions</h2>


    <table>
      <thead>
        <tr>

          <th>First Name</th>
          <th>Last Name</th>
          <th>Date Joined</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><a href="{% url 'friend:profile' id=most.id %}"> {{most.first_name}}</a></td>
          <td>{{most.last_name}}</td>
          <td>{{most.created_at}}</td>
        </tr>
        <tr>
          <td><a href="{% url 'friend:profile' id=more.id %}">{{more.first_name}}</a></td>
          <td>{{more.last_name}}</td>
          <td>{{more.created_at}}</td>
        </tr>
        <tr>
          <td><a href="{% url 'friend:profile' id=recents.id %}">{{recents.first_name}}</a></td>
          <td>{{recents.last_name}}</td>
          <td>{{recents.created_at}}</td>
        </tr>
      </tbody>
    </table>
  </body>
</html>

apps/friend/templates/friend/list.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>People who you think you are already friends with</h1>
    <a href="{% url 'friend:index' %}">Home</a>
    {% if friends %}
    <h1>Friends List</h1>
    {% else %}
    <h1>No one loves you</h1>
    {% endif %}

    {% for friend in friends %}
    <table>
      <tr>
        <td><a href="{% url 'friend:profile' id=friend.id %}">{{friend.first_name}}</a></td>
        <td>{{friend.last_name}}</td>
        <td><a href="{% url 'friend:remove' id=friend.id %}">Delete them they suck</a></td>
      </tr>
    </table>
    {% endfor %}
    {% if blocks %}
    <h1>Bishes youve blocked</h1>
    {% else %}
    <h1>You dont think anyones crazy</h1>
    {% endif %}

    {% for block in blocks %}
    <table>
      <tr>
        <td><a href="{% url 'friend:profile' id=block.id %}">{{block.first_name}}</a></td>
        <td>{{block.last_name}}</td>
        <td><a href="{% url 'friend:remove_block' id=block.id %}">I changed my mind they are okay</a></td>
      </tr>
    </table>
    {% endfor %}
  </body>
</html>

apps/friend/templates/friend/profile.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
  <h1>Profile Page</h1>
  <a href="{% url 'friend:index' %}">Home</a>

  <h1>{{friend.first_name}}</h1>
  <h1>{{friend.last_name}}</h1>
  <h2>{{friend.email}}</h2>
  <h2>Joined {{friend.created_at}}</h2>
  </body>
</html>